# Generated by Django 4.0.4 on 2022-05-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('DateOfBirth', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=5)),
                ('ResidentialAddress', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=20)),
            ],
        ),
    ]
